path: /Users/alberto/ROBOTICS/test_scrips/data
train: images/train
val: images/val
test: images/test

nc: 2
names: ['autovelox', 'controllo velocita']

roboflow:
  workspace: university-qidrm
  project: autovelox-detection
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/university-qidrm/autovelox-detection/dataset/2
  