#path: /Users/alberto/ROBOTICS/autovelox_detector_project/data
path: /Users/alberto/Desktop/FINAL_DATASET/TWO_ASSIGNS_AUG/data
train: images/train
val: images/val
test: images/test

# Number of classes
nc: 11

# Classes
names:
  0: X1-Y1-Z2
  1: X1-Y2-Z1
  2: X1-Y2-Z2
  3: X1-Y2-Z2-CHAMFER
  4: X1-Y2-Z2-TWINFILLET
  5: X1-Y3-Z2
  6: X1-Y3-Z2-FILLET
  7: X1-Y4-Z1
  8: X1-Y4-Z2
  9: X2-Y2-Z2
  10: X2-Y2-Z2-FILLET

roboflow:
  workspace: university-qidrm
  project: mega-blocks-detection
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/university-qidrm/mega-blocks-detection/dataset/1
  